function(AddHIP)
  set(options)
  set(oneValueArgs HIP_SDK)
  set(multiValueArgs)
  cmake_parse_arguments(arg "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN} )

  set(HIP_SDK HIP PARENT_SCOPE)
  if (CMAKE_SYSTEM_NAME STREQUAL Windows)
    add_library(hip::include IMPORTED INTERFACE)
	target_include_directories(hip::include INTERFACE ${arg_HIP_SDK}/include)
    add_library(hip::host IMPORTED STATIC)
    set_target_properties(hip::host PROPERTIES IMPORTED_LOCATION ${arg_HIP_SDK}/lib/amdhip64.lib)
    add_library(hip IMPORTED INTERFACE)
    target_link_libraries(hip INTERFACE hip::include hip::host)

	set(hip_INCLUDE_DIRS ${arg_HIP_SDK}/include PARENT_SCOPE)
  else()
    # Linux/Unix systems
    add_library(hip::include IMPORTED INTERFACE)
    target_include_directories(hip::include INTERFACE ${arg_HIP_SDK}/include)
    add_library(hip::host IMPORTED SHARED)
    set_target_properties(hip::host PROPERTIES IMPORTED_LOCATION ${arg_HIP_SDK}/lib/libamdhip64.so)
    add_library(hip IMPORTED INTERFACE)
    target_link_libraries(hip INTERFACE hip::include hip::host)

	set(hip_INCLUDE_DIRS ${arg_HIP_SDK}/include PARENT_SCOPE)
  endif()
endfunction()
