function(AddHIP)
  set(options)
  set(oneValueArgs HIP_DIR)
  set(multiValueArgs)
  cmake_parse_arguments(arg "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN} )

  set(HIP_DIR HIP PARENT_SCOPE)
  if (CMAKE_SYSTEM_NAME STREQUAL Windows)
    add_library(hip::include IMPORTED INTERFACE)
    target_include_directories(hip::include INTERFACE ${arg_HIP_DIR}/include)
    add_library(hip::host IMPORTED STATIC)
    set_target_properties(hip::host PROPERTIES IMPORTED_LOCATION ${arg_HIP_DIR}/lib/amdhip64.lib)
    add_library(hip IMPORTED INTERFACE)
    target_link_libraries(hip INTERFACE hip::include hip::host)
  else()
    # Linux/Unix systems
    add_library(hip::include IMPORTED INTERFACE)
    target_include_directories(hip::include INTERFACE ${arg_HIP_DIR}/include)
    add_library(hip::host IMPORTED SHARED)
    set_target_properties(hip::host PROPERTIES IMPORTED_LOCATION ${arg_HIP_DIR}/lib/libamdhip64.so)
    add_library(hip IMPORTED INTERFACE)
    target_link_libraries(hip INTERFACE hip::include hip::host)
  endif()
endfunction()